name: Preview

on: pull_request

jobs:
  distribute-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa_github_actions
          known_hosts: unnecessary
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: |
          yarn

      - name: Preview app on Appetize 🚀
        run: bundle exec fastlane ios preview
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SOURCE_BRANCH: ${{ github.head_ref }}
          APPETIZE_API_TOKEN: ${{ secrets.APPETIZE_API_TOKEN }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
