name: Preview

on: pull_request

jobs:
  distribute-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: |
          yarn

      - name: Preview app on Appetize 🚀
        run: bundle exec fastlane ios preview
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SOURCE_BRANCH: ${{ github.head_ref }}
          APPETIZE_API_TOKEN: ${{ secrets.APPETIZE_API_TOKEN }}
